/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BooksSetObjectPageObjectPage journey");

        opaTest("Navigate to BooksSetObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheBooksSetListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheBooksSetListGenerated.onTable().iCheckRows();
            When.onTheBooksSetListGenerated.onTable().iPressRow(0);

            Then.onTheBooksSetObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheBooksSetObjectPageGenerated.iCheckNumberOfSections(3);
        });

        opaTest("Check the FieldGroup::General section of the Object Page", function (_Given, When, Then) {
            When.onTheBooksSetObjectPageGenerated.iGoToSection({ section: "FieldGroup::General" });
            Then.onTheBooksSetObjectPageGenerated.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheBooksSetObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "title" });
            Then.onTheBooksSetObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "author" });
            Then.onTheBooksSetObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "ageGroup" });
            Then.onTheBooksSetObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "gender" });
        });

        opaTest("Check the FieldGroup::Publication section of the Object Page", function (_Given, When, Then) {
            When.onTheBooksSetObjectPageGenerated.iGoToSection({ section: "FieldGroup::Publication" });
            Then.onTheBooksSetObjectPageGenerated.iCheckSection({ section: "FieldGroup::Publication" });
            Then.onTheBooksSetObjectPageGenerated.onForm({ section: "FieldGroup::Publication" }).iCheckField({ property: "publishedDate" });
        });

        opaTest("Check the FieldGroup::Pricing section of the Object Page", function (_Given, When, Then) {
            When.onTheBooksSetObjectPageGenerated.iGoToSection({ section: "FieldGroup::Pricing" });
            Then.onTheBooksSetObjectPageGenerated.iCheckSection({ section: "FieldGroup::Pricing" });
            Then.onTheBooksSetObjectPageGenerated.onForm({ section: "FieldGroup::Pricing" }).iCheckField({ property: "price" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});